import type { NextComponentType } from "next";
import Head from "next/head";
import React from "react";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import LocalLibraryIcon from "@mui/icons-material/LocalLibrary";
import MenuBookIcon from "@mui/icons-material/MenuBook";
import ArchiveIcon from "@mui/icons-material/Archive";
import HelpCenterIcon from "@mui/icons-material/HelpCenter";

const Home: NextComponentType = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-container pt-8">
        <div className={windStyles.wrapper}>
          <div className="header min-h-screen">
            <div className="header-upper">
              <ul className={windStyles.menu}>
                <li className="hover:text-lime-600">
                  <Link href="/meetings">заседания</Link>
                </li>
                <li className={windStyles.link}>
                  <Link href="/">интересные материалы</Link>
                </li>
                <li className={windStyles.link}>
                  <Link href="/">наша команда</Link>
                </li>
                <li className={windStyles.link}>
                  <Link href="/">поделиться редкой книгой</Link>
                </li>
              </ul>
              <div className="line pt-2">
                <hr className="border-t-2 border-black" />
              </div>
            </div>
            <div className="title mt-12">
              <div className="title-main  text-4xl md:text-5xl text-center">
                учебно-методическая группа
              </div>
              <div className="title-sub  text-2xl md:text-4xl pt-4 text-center">
                по арбитражному процессу
              </div>
            </div>
            <div className="main flex justify-between pt-36">
              <div className="events md:w-1/3">
                <div className={`${styles.title} title`}>
                  предстоящие заседания
                </div>
                <div className="title-sub  text-xl mt-12">
                  на данный момент заседаний не планируется
                </div>
              </div>
              <div className="links text-xl mt-4">
                <Link href="/guide" passHref>
                  <p className="cursor-pointer hover:text-lime-600 mb-4">
                    <LocalLibraryIcon
                      fontSize="large"
                      className="mr-2 text-zinc-300"
                    />
                    гайд для аспирантов
                  </p>
                </Link>
                <Link href="/literature" passHref>
                  <p className="cursor-pointer hover:text-lime-600 mb-4">
                    <MenuBookIcon
                      fontSize="large"
                      className="mr-2 text-zinc-300"
                    />
                    литература
                  </p>
                </Link>
                <Link href="/archive" passHref>
                  <p className="cursor-pointer hover:text-lime-600 mb-4">
                    <ArchiveIcon
                      fontSize="large"
                      className="mr-2 text-zinc-300"
                    />
                    архив объявлений
                  </p>
                </Link>
                <button>
                  <p className="hover:text-lime-600 ">
                    <HelpCenterIcon
                      fontSize="large"
                      className="mr-2 text-zinc-300 "
                    />
                    вопросы? напишите нам
                  </p>
                </button>
              </div>
            </div>
            {/* <div className="img text-center">
              <Image
                src="/images/pirosmani.jpg"
                alt="pirosmani"
                width="850px"
                height="350px"
              />
            </div> */}
          </div>
        </div>
      </div>
    </>
  );
};

export default Home;

const windStyles = {
  wrapper: "wrapper w-11/12 md:w-11/12 lg:w-4/5 m-auto xl:w-3/5",
  menu: "menu flex justify-between font-bold",
  link: "hover:text-lime-600",
};
