import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import HomeSection from "../sections/HomeSection";
import TeamSection from "../sections/TeamSection";
import ClassicsSection from "../sections/ClassicsSection";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>APKRF.NET</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeSection />
      <ClassicsSection />
      <TeamSection />
    </>
  );
};

export default Home;

// const windStyles = {
//   wrapper: "wrapper w-11/12 md:w-11/12 lg:w-4/5 m-auto xl:w-3/5",
// };
